//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was 'partially' generated by the 'Component Based Clean Swift Templates' created by Jovan Radivojsa (a.k.a. joxoleon),
//  Based on the clean swift templates created by Raymond Law: http://clean-swift.com
//

import UIKit

protocol ___VARIABLE_sceneName___PresentationLogic: PresentationLogic {
    // func presentSomething(_ response: ___VARIABLE_sceneName___.Something.Response)
}

class ___VARIABLE_sceneName___Presenter: BasePresenter, ___VARIABLE_sceneName___PresentationLogic {

    struct Constants {
        // static let UserNameTextColor = UIColor.black
    }

    // MARK: - Scene Component Properties
    weak var viewController: ___VARIABLE_sceneName___DisplayLogic? {
        return baseViewController as? ___VARIABLE_sceneName___DisplayLogic
    }

    // MARK: - Properties
    // var isSomething: Bool = true

    // MARK: - Presentation logic

    // func presentSomething(_ response: ___VARIABLE_sceneName___.Something.Response) {
    //     viewController?.displaySomething(___VARIABLE_sceneName___.Something.ViewModel())
    // }

    // MARK: - Utility

}
