//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was 'partially' generated by the 'Component Based Clean Swift Templates' created by Jovan Radivojsa (a.k.a. joxoleon)
//  Based on the clean swift templates created by Raymond Law: http://clean-swift.com
//

import UIKit

protocol ___VARIABLE_sceneName___DisplayLogic: DisplayLogic {
    // func displaySomething(_ viewModel: ___VARIABLE_sceneName___.Something.ViewModel)
}

class ___VARIABLE_sceneName___ViewController: BaseViewController {

    // MARK: - Scene Component Properties
    var configurator: ___VARIABLE_sceneName___Configurator? { // Solely for testing purposes
        return baseConfigurator as? ___VARIABLE_sceneName___Configurator
    }
    var interactor: ___VARIABLE_sceneName___BusinessLogic? {
        return baseInteractor as? ___VARIABLE_sceneName___BusinessLogic
    }
    var router: ___VARIABLE_sceneName___RouterInput? {
        return baseRouter as? ___VARIABLE_sceneName___RouterInput
    }

    // MARK: Properties
    // var isSomething: Bool = true

    // Mark: - Outlets
    //@IBOutlet weak var nameTextField: UITextField!

    // MARK: - Object Lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        baseConfigurator = ___VARIABLE_sceneName___Configurator()
        configurator?.configure(self)
    }
    
    // MARK: - View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Perform initialization of the scene
        // interactor?.doSomething()
    }
}

extension ___VARIABLE_sceneName___ViewController: ___VARIABLE_sceneName___DisplayLogic {

    // MARK: - Display Logic

    // func displaySomething(_ viewModel: ___VARIABLE_sceneName___.Something.ViewModel) {
    //     nameTextField.text = viewModel.name
    // }

    // MARK: - Utility Methods
}
