//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was 'partially' generated by the 'Component Based Clean Swift Templates' created by Jovan Radivojsa (a.k.a. joxoleon)
//  Based on the clean swift templates created by Raymond Law: http://clean-swift.com
//

import UIKit

class ___VARIABLE_sceneName___Worker: BaseWorker {
}
