//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was 'partially' generated by the 'Component Based Clean Swift Templates' created by Jovan Radivojsa (a.k.a. joxoleon)
//  Based on the clean swift templates created by Raymond Law: http://clean-swift.com
//

import UIKit

protocol ___VARIABLE_sceneName___RoutingNavigation: RoutingNavigation {
    func showNewScreen()
}

protocol ___VARIABLE_sceneName___DataPassing: DataPassing {}

typealias ___VARIABLE_sceneName___RouterInput = ___VARIABLE_sceneName___RoutingNavigation & ___VARIABLE_sceneName___DataPassing

class ___VARIABLE_sceneName___Router: BaseRouter, ___VARIABLE_sceneName___RouterInput {
    
    private struct Segues {
        static let ShowNextScreenIdentifier = ""
    }

    // MARK: - Scene Components
    var dataStore: ___VARIABLE_sceneName___DataStore? {
        return baseDataStore as? ___VARIABLE_sceneName___DataStore
    }
    weak var viewController: ___VARIABLE_sceneName___ViewController? {
        return baseViewController as? ___VARIABLE_sceneName___ViewController
    }

    // MARK: - Properties
    // var isSomething: Bool = true

    // MARK: Navigation

    func showNewScreen() {
        performSegueWithIdentifier(segueId: Segues.ShowNextScreenIdentifier)
    }

    // MARK: Passing data

    override func passDataToNextScene(segue: UIStoryboardSegue) {
        if segue.identifier == Segues.ShowNextScreenIdentifier {
            // Pass Relevant Data
        }
    }
}
