//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was 'partially' generated by the 'Component Based Clean Swift Templates' created by Jovan Radivojsa (a.k.a. joxoleon),
//  Based on the clean swift templates created by Raymond Law: http://clean-swift.com
//

import UIKit

struct ___VARIABLE_sceneName___: Models {

    // MARK: - Data definitions

    // MARK: - Use cases

    // struct Something {
    //     struct Request {
    //     }
    //     struct Response {
    //     }
    //     struct ViewModel {
    //     }
    // }
}
