//
//  TestInteractor.swift
//  TemplatesTestProject
//
//  Created by Jovan on 4/14/19.
//  Copyright (c) 2019 Jovan. All rights reserved.
//
//  This file was 'partially' generated by the 'Component Based Clean Swift Templates' created by Jovan Radivojsa (a.k.a. joxoleon),
//  Based on the clean swift templates created by Raymond Law: http://clean-swift.com
//

import UIKit

protocol TestBusinessLogic: BusinessLogic {
    func onViewDidLoad()
    func onViewWillAppear()
}

protocol TestDataStore: DataStore {
}

class TestInteractor: BaseInteractor, TestBusinessLogic, TestDataStore {

    // MARK: - Scene Component Properties
    var presenter: TestPresentationLogic? {
        return basePresenter as? TestPresentationLogic
    }
    var worker: TestWorker? {
        return baseWorker as? TestWorker
    }

    // MARK: - Properties

    // MARK: - Override Base Methods

    override func onBaseChildViewControllerClosing(childDataStore: DataStore) {
        // Called from base when child data store is closing - user childDataStore to receive data from the child scene
    }

    // MARK: - Business Logic

    func onViewDidLoad() {
    }

    func onViewWillAppear() {
    }

    // MARK: - Utility Methods
}
