//
//  TestModels.swift
//  TemplatesTestProject
//
//  Created by Jovan on 4/14/19.
//  Copyright (c) 2019 Jovan. All rights reserved.
//
//  This file was 'partially' generated by the 'Component Based Clean Swift Templates' created by Jovan Radivojsa (a.k.a. joxoleon),
//  Based on the clean swift templates created by Raymond Law: http://clean-swift.com
//

import UIKit

struct Test: ModelsBase {

    // MARK: - Data definitions

    // MARK: - Use cases

    struct ViewDidLoad {
        struct Request: RequestBase {

        }
        struct Response: ResponseBase {

        }
        struct ViewModel: ViewModelBase {

        }
    }

    struct ViewWillAppear {
        struct Request: RequestBase {

        }
        struct Response: ResponseBase {

        }
        struct ViewModel: ViewModelBase {

        }
    }
}
