//
//  TestPresenter.swift
//  TemplatesTestProject
//
//  Created by Jovan on 4/14/19.
//  Copyright (c) 2019 Jovan. All rights reserved.
//
//  This file was 'partially' generated by the 'Component Based Clean Swift Templates' created by Jovan Radivojsa (a.k.a. joxoleon),
//  Based on the clean swift templates created by Raymond Law: http://clean-swift.com
//

import UIKit

protocol TestPresentationLogic: PresentationLogic {
    func presentOnViewDidLoad(_ response: Test.ViewDidLoad.Response)
    func presentOnViewWillAppear(_ response: Test.ViewWillAppear.Response)
}

class TestPresenter: BasePresenter, TestPresentationLogic {

    struct Constants {
    }

    // MARK: - Scene Component Properties
    weak var viewController: TestDisplayLogic? {
        return baseViewController as? TestDisplayLogic
    }

    // MARK: - Properties

    // MARK: - Presentation logic

    func presentOnViewDidLoad(_ response: Test.ViewDidLoad.Response) {
    }

    func presentOnViewWillAppear(_ response: Test.ViewWillAppear.Response) {
    }

    // MARK: - Utility

    // func isSomethingSomething() -> Bool { return true }
}
