//
//  TestConfigurator.swift
//  TemplatesTestProject
//
//  Created by Jovan on 4/14/19.
//  Copyright (c) 2019 Jovan. All rights reserved.
//
//  This file was 'partially' generated by the 'Component Based Clean Swift Templates' created by Jovan Radivojsa (a.k.a. joxoleon),
//  Based on the clean swift templates created by Raymond Law: http://clean-swift.com
//

import UIKit

// Connects View, Interactor, and Presenter
class TestConfigurator: BaseConfigurator {

    func configure(_ viewController: TestViewController) {
        // Instantiate scene components.
        let presenter = TestPresenter()
        let worker = TestWorker()
        let interactor = TestInteractor()
        let router = TestRouter()

        // Set configurator variables and connect them.
        self.baseViewController = viewController
        self.baseWorker = worker
        self.basePresenter = presenter
        self.baseInteractor = interactor
        self.baseRouter = router
    }
}
