//
//  TestViewController.swift
//  TemplatesTestProject
//
//  Created by Jovan on 4/14/19.
//  Copyright (c) 2019 Jovan. All rights reserved.
//
//  This file was 'partially' generated by the 'Component Based Clean Swift Templates' created by Jovan Radivojsa (a.k.a. joxoleon)
//  Based on the clean swift templates created by Raymond Law: http://clean-swift.com
//

import UIKit

protocol TestDisplayLogic: DisplayLogic {
    func displayOnViewDidLoad(_ viewModel: Test.ViewDidLoad.ViewModel)
    func displayOnViewWillAppear(_ viewModel: Test.ViewWillAppear.ViewModel)
}

class TestViewController: BaseViewController {

    // MARK: - Scene Component Properties And Configuration
    var configurator: TestConfigurator? { // Solely for testing purposes
        return baseConfigurator as? TestConfigurator
    }
    var interactor: TestBusinessLogic? {
        return baseInteractor as? TestBusinessLogic
    }
    var router: TestRouterInput? {
        return baseRouter as? TestRouterInput
    }

    override func awakeFromNib() {
        super.awakeFromNib()
        baseConfigurator = TestConfigurator()
        configurator?.configure(self)
    }

    // MARK: Properties

    // Mark: - Outlets

    // MARK: - Actions

    // MARK: - Override Base Methods

    override func onViewDidLoad() {
        // Called automatically from base - Add your 'onViewDidLoad' logic here.
        interactor?.onViewDidLoad()
    }

    override func onViewWillAppear() {
        // Called automatically from base - Add your 'onViewWillAppear' logic here.
        interactor?.onViewWillAppear()
    }
}

extension TestViewController: TestDisplayLogic {

    // MARK: - Display Logic

    func displayOnViewDidLoad(_ viewModel: Test.ViewDidLoad.ViewModel) {
    }

    func displayOnViewWillAppear(_ viewModel: Test.ViewWillAppear.ViewModel) {
    }

    // MARK: - Utility Methods
}
