//
//  BaseInteractor.swift
//  CleanSwiftTestProject
//
//  Created by Jovan on 4/13/19.
//  Copyright (c) 2019 Jovan. All rights reserved.
//
//  This file was 'partially' generated by the Clean Swift templates created by Jovan Radivojsa (a.k.a. joxoleon),
//  Based on the original clean swift templates created by Raymond Law: http://clean-swift.com
//

import UIKit

class BaseInteractor: BusinessLogic, DataStore {

    // MARK: - Scene Component Properties
    var basePresenter: PresentationLogic?
    var baseWorker: WorkerLogic?

    // MARK: - Base Methods

    func onBaseChildViewControllerClosing(childDataStore: DataStore) {
        // Use 'childDataStore' to extract necessary data from the closing child view controller.
    }

    func businessLogicOnViewDidLoad() { /* Override in concrete interactor */}

    func businessLogicOnViewWillAppear() { /* Override in concrete interactor */ }
}
